package models

var StandardTags = map[Slug]string{
	"foxgirl":                             "Fox Girl",
	"monstergirl":                         "Monster Girl",
	"ai":                                  "AI",
	"aiassistant":                         "AI Assistant",
	"alternategreetings":                  "Alternate Greetings",
	"ntrbait":                             "NTR Bait",
	"ntrrevenge":                          "NTR Revenge",
	"comic":                               "Comic Book",
	"waiter":                              "Waiter/Waitress",
	"massuese":                            "Masseuse",
	"masseuse":                            "Masseuse",
	"first":                               "First Person",
	"second":                              "Second Person",
	"third":                               "Third Person",
	"plist":                               "Plist",
	"smut":                                "Smut",
	"cnc":                                 "Consensual Non-Consent",
	"cbt":                                 "Cock And Ball Torture",
	"watersports":                         "Water Sports",
	"featuredcreator":                     "Featured CreatorInfo",
	"vtuber":                              "VTuber",
	"wellintentionedextremist":            "Well Intentioned Extremist",
	"parentplay":                          "Parent Play",
	"sizeplay":                            "Size Play",
	"analplay":                            "Anal Play",
	"raceplay":                            "Race Play",
	"freeuse":                             "Free Use",
	"wetandmessy":                         "Wet And Messy",
	"facesitting":                         "Face Sitting",
	"breastmilk":                          "Breast Milk",
	"fearplay":                            "Fear Play",
	"praisekink":                          "Praise Kink",
	"orgasmcontrol":                       "Orgasm Control",
	"masterslave":                         "Master-Slave",
	"roleplaying":                         "Role-Playing",
	"sensorydeprivation":                  "Sensory Deprivation",
	"temperatureplay":                     "Temperature Play",
	"electroplay":                         "Electro Play",
	"petplay":                             "Pet Play",
	"scentplay":                           "Scent Play",
	"waxplay":                             "Wax Play",
	"knifeplay":                           "Knife Play",
	"bloodplay":                           "Blood Play",
	"reverseharem":                        "Reverse Harem",
	"exoticdancer":                        "Exotic Dancer",
	"pornstar":                            "Porn Star",
	"earplay":                             "Ear Play",
	"impactplay":                          "Impact Play",
	"breathplay":                          "Breath Play",
	"prisonguard":                         "Prison Guard",
	"testsubject":                         "Test Subject",
	"bountyhunter":                        "Bounty Hunter",
	"conartist":                           "Con Artist",
	"trickstermentor":                     "Trickster Mentor",
	"reluctanthero":                       "Reluctant Hero",
	"brokenbird":                          "Broken Bird",
	"gentlegiant":                         "Gentle Giant",
	"chaoticneutral":                      "Chaotic Neutral",
	"eternaloptimist":                     "Eternal Optimist",
	"lovablerogue":                        "Lovable Rogue",
	"ghosthunter":                         "Ghost Hunter",
	"monsterhunter":                       "Monster Hunter",
	"wishfulfillment":                     "Wish Fulfillment",
	"sliceoflife":                         "Slice Of Life",
	"tvshow":                              "TV Show",
	"videogame":                           "Video Game",
	"kpop":                                "K-Pop",
	"reverserape":                         "Reverse Rape",
	"bdsm":                                "BDSM",
	"nsfw":                                "NSFW",
	"oc":                                  "OC",
	"roleplay":                            "Role-Play",
	"fempov":                              "Fem POV",
	"malepov":                             "Male POV",
	"milf":                                "MILF",
	"ntr":                                 "NTR",
	"sfwnsfw":                             "SFW <-> NSFW",
	"antintr":                             "Anti-NTR",
	"nsfl":                                "NSFL",
	"sillytavern":                         "Silly Tavern",
	"thebasement":                         "The Basement",
	"possiblentr":                         "Possible NTR",
	"thickmilf":                           "Thick MILF",
	"sfw":                                 "SFW",
	"wlw":                                 "WLW",
	"jed":                                 "JED",
	"missteacher":                         "Miss Teacher",
	"nonhumancharacter":                   "Non-Human Character",
	"possiblentrifyoutryreallyreallyhard": "Possible NTR If You Try Really Really Hard",
	"ntravoidable":                        "NTR Avoidable",
	"femboypov":                           "Femboy POV",
	"nonenglish":                          "Non-English",
	"shotapov":                            "Shota POV",
	"duelmonsters":                        "Duel Monsters",
	"milfwife":                            "Milf Wife",
	"risuai":                              "RisuAI",
	"bbw":                                 "BBW",
	"cai":                                 "CAI",
	"harmonytown":                         "Harmony Town",
	"ptsd":                                "PTSD",
	"reversentr":                          "Reverse NTR",
	"sph":                                 "SPH",
	"gf":                                  "GF",
	"xml":                                 "XML",
	"darkskinned":                         "Dark Skinned",
	"futapov":                             "Futa POV",
	"rnuclearrevenge":                     "R/NuclearRevenge",
	"yta":                                 "YTA",
	`"ntr"`:                               `"NTR"`,
	"anypov":                              "Any POV",
	"canbeanypovbutmadewithmalepovinmind": "Can Be Any POV But Made With Male POV In Mind",
	"possiblebdsm":                        "Possible BDSM",
	"oai":                                 "OAI",
	"alichat":                             "Ali:Chat",
	"slightdom":                           "Slight Dom",
}

func ResolveTag(stringTag string) Tag {
	slug := SanitizeSlug(stringTag)
	if standardName, ok := StandardTags[slug]; ok {
		return Tag{Slug: slug, Name: standardName}
	}
	return Tag{Slug: slug, Name: SanitizeName(stringTag)}
}
